[package]
name = "simd_demo"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5"



[profile.release]
panic = "abort"
lto = "thin"

[[bench]]
name = "matmul"
harness = false