[build]
rustflags = "-C target-cpu=native"

# [target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
# rustflags = "-C target-cpu=native"
# rustflags = ["-C", "target-feature=+avx,+avx2,+avx512f,+avx512vl,+avx512bw,+avx512cd,+avx512vnni,+avx512ifma,+avx512dq,+avx512vbmi,+avx512vbmi2,+fma"]